name: meetup
description: A social media app.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^1.0.4
  camera: ^0.10.5+5
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
